### ISSUE TITLE
wstool update failure

### ISSUE THREAD

**Issue by HashirZahir** [unr-arl/gbplanner_ws#2]
Hi, thanks for all the amazing work. I just wanted to point out that there were 2 caveats when following the current instructions on building the repository. First of all, it must be cloned via ssh, not https since the `packages.rosinstall` file uses git ssh specific URLs. 

That aside, the `glog_catkin` package specified in the `packages.rosinstall` does not exist under the unr-arl organization. I am guessing it is referring to [this](https://github.com/ethz-asl/glog_catkin) package instead. Otherwise, I was able to build the repo / workspace successfully. Just a note in case this can help someone. Thanks.

**Comment by tungdanganh** [comment]
Thanks a lot @HashirZahir I've updated the repo accordingly.
